# Generated by Django 4.0.3 on 2022-04-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='date_uploaded',
        ),
    ]
