# Generated by Django 4.0.3 on 2022-04-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_deck_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
