# Generated by Django 4.0.3 on 2022-04-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_deck_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rented', models.DateTimeField(auto_now_add=True)),
                ('date_return', models.DateTimeField(blank=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.deck')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.profile')),
            ],
        ),
    ]
