# Generated by Django 4.0.3 on 2022-04-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
