# Generated by Django 4.0.3 on 2022-03-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mini_fb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.TextField(blank=True)),
                ('Last_name', models.TextField(blank=True)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
