# Generated by Django 4.0.3 on 2022-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_remove_mini_fb_image_mini_fb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='mini_fb',
        ),
    ]
