# Generated by Django 4.0.3 on 2022-04-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_statusmessage_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='mini_fb.profile'),
        ),
    ]
